<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFrameworks>net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
        <!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
        <!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->

        <!-- Note for MacCatalyst:
            The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
            When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
            The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
            either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
        <!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

        <OutputType>Exe</OutputType>
        <RootNamespace>GreenGleam.App</RootNamespace>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
        <ImplicitUsings>enable</ImplicitUsings>
        <EnableDefaultCssItems>false</EnableDefaultCssItems>
        <Nullable>enable</Nullable>

        <!-- Display name -->
        <ApplicationTitle>GreenGleam.App</ApplicationTitle>

        <!-- App Identifier -->
        <ApplicationId>com.companyname.greengleam.app</ApplicationId>

        <!-- Versions -->
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <ApplicationVersion>1</ApplicationVersion>

        <!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
        <WindowsPackageType>None</WindowsPackageType>

        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
        <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
    </PropertyGroup>

    <ItemGroup>
        <!-- App Icon -->
        <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

        <!-- Splash Screen -->
        <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

        <!-- Images -->
        <MauiImage Include="Resources\Images\*" />

        <!-- Custom Fonts -->
        <MauiFont Include="Resources\Fonts\*" />

        <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
        <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>

    <ItemGroup>
      <AndroidResource Remove="Apis\wwwroot\**" />
      <Compile Remove="Apis\wwwroot\**" />
      <Content Remove="Apis\wwwroot\**" />
      <EmbeddedResource Remove="Apis\wwwroot\**" />
      <MauiXaml Remove="Apis\wwwroot\**" />
      <None Remove="Apis\wwwroot\**" />
    </ItemGroup>

    <ItemGroup>
      <MauiImage Include="wwwroot\image\product\apple.png" />
      <MauiImage Include="wwwroot\image\product\apricot.png" />
      <MauiImage Include="wwwroot\image\product\arugula.png" />
      <MauiImage Include="wwwroot\image\product\asparagus.png" />
      <MauiImage Include="wwwroot\image\product\avocado.png" />
      <MauiImage Include="wwwroot\image\product\banana.png" />
      <MauiImage Include="wwwroot\image\product\basil.png" />
      <MauiImage Include="wwwroot\image\product\beet.png" />
      <MauiImage Include="wwwroot\image\product\bell_pepper.png" />
      <MauiImage Include="wwwroot\image\product\berries.png" />
      <MauiImage Include="wwwroot\image\product\blueberry.png" />
      <MauiImage Include="wwwroot\image\product\broccoli.png" />
      <MauiImage Include="wwwroot\image\product\brussels_sprouts.png" />
      <MauiImage Include="wwwroot\image\product\cabbage.png" />
      <MauiImage Include="wwwroot\image\product\caper.png" />
      <MauiImage Include="wwwroot\image\product\carambola.png" />
      <MauiImage Include="wwwroot\image\product\carrot.png" />
      <MauiImage Include="wwwroot\image\product\cauliflower.png" />
      <MauiImage Include="wwwroot\image\product\celery.png" />
      <MauiImage Include="wwwroot\image\product\cherry.png" />
      <MauiImage Include="wwwroot\image\product\chestnut.png" />
      <MauiImage Include="wwwroot\image\product\chili_pepper.png" />
      <MauiImage Include="wwwroot\image\product\coconut.png" />
      <MauiImage Include="wwwroot\image\product\corn.png" />
      <MauiImage Include="wwwroot\image\product\cucumber.png" />
      <MauiImage Include="wwwroot\image\product\date.png" />
      <MauiImage Include="wwwroot\image\product\dill.png" />
      <MauiImage Include="wwwroot\image\product\eggplant.png" />
      <MauiImage Include="wwwroot\image\product\fig.png" />
      <MauiImage Include="wwwroot\image\product\garlic.png" />
      <MauiImage Include="wwwroot\image\product\ginger.png" />
      <MauiImage Include="wwwroot\image\product\goji.png" />
      <MauiImage Include="wwwroot\image\product\gooseberry.png" />
      <MauiImage Include="wwwroot\image\product\grapefruit.png" />
      <MauiImage Include="wwwroot\image\product\grapes.png" />
      <MauiImage Include="wwwroot\image\product\guava.png" />
      <MauiImage Include="wwwroot\image\product\horseradish.png" />
      <MauiImage Include="wwwroot\image\product\kiwi.png" />
      <MauiImage Include="wwwroot\image\product\kohlrabi.png" />
      <MauiImage Include="wwwroot\image\product\kumquat.png" />
      <MauiImage Include="wwwroot\image\product\leek.png" />
      <MauiImage Include="wwwroot\image\product\lemon.png" />
      <MauiImage Include="wwwroot\image\product\lettuce.png" />
      <MauiImage Include="wwwroot\image\product\lime.png" />
      <MauiImage Include="wwwroot\image\product\mango.png" />
      <MauiImage Include="wwwroot\image\product\mangosteen.png" />
      <MauiImage Include="wwwroot\image\product\melon.png" />
      <MauiImage Include="wwwroot\image\product\olives.png" />
      <MauiImage Include="wwwroot\image\product\orange.png" />
      <MauiImage Include="wwwroot\image\product\papaya.png" />
      <MauiImage Include="wwwroot\image\product\parsley.png" />
      <MauiImage Include="wwwroot\image\product\passion_fruit.png" />
      <MauiImage Include="wwwroot\image\product\peach.png" />
      <MauiImage Include="wwwroot\image\product\pear.png" />
      <MauiImage Include="wwwroot\image\product\peas.png" />
      <MauiImage Include="wwwroot\image\product\persimmon.png" />
      <MauiImage Include="wwwroot\image\product\pineapple.png" />
      <MauiImage Include="wwwroot\image\product\plum.png" />
      <MauiImage Include="wwwroot\image\product\pomegranate.png" />
      <MauiImage Include="wwwroot\image\product\potato.png" />
      <MauiImage Include="wwwroot\image\product\pumpkin.png" />
      <MauiImage Include="wwwroot\image\product\quince.png" />
      <MauiImage Include="wwwroot\image\product\radish.png" />
      <MauiImage Include="wwwroot\image\product\rambutan.png" />
      <MauiImage Include="wwwroot\image\product\raspberry.png" />
      <MauiImage Include="wwwroot\image\product\rhubarb.png" />
      <MauiImage Include="wwwroot\image\product\spinach.png" />
      <MauiImage Include="wwwroot\image\product\squash.png" />
      <MauiImage Include="wwwroot\image\product\strawberry.png" />
      <MauiImage Include="wwwroot\image\product\sweet_potato.png" />
      <MauiImage Include="wwwroot\image\product\tomato.png" />
      <MauiImage Include="wwwroot\image\product\turnip.png" />
      <MauiImage Include="wwwroot\image\product\watermelon.png" />
      <MauiImage Include="wwwroot\image\product\zucchini.png" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="$(MauiVersion)" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0" />
        <PackageReference Include="Refit.HttpClientFactory" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GreenGleam.Shared\GreenGleam.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Include="wwwroot\image\product\bell_pepper.png" />
      <None Include="wwwroot\image\product\brussels_sprouts.png" />
      <None Include="wwwroot\image\product\chili_pepper.png" />
      <None Include="wwwroot\image\product\passion_fruit.png" />
      <None Include="wwwroot\image\product\sweet_potato.png" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Resources\Images\" />
    </ItemGroup>

</Project>
