// <auto-generated />
using System;
using GreenGleam.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenGleam.Api.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250902025743_FixedTypo")]
    partial class FixedTypo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenGleam.Api.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int");

                    b.Property<int>("UserAddressId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GreenGleam.Api.Data.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("GreenGleam.Api.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sweet and tart blueberries packed with antioxidants.",
                            Image = "image/product/blueberry.png",
                            Name = "Blueberry",
                            Price = 250.00m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Crunchy carrots full of vitamins and nutrients.",
                            Image = "image/product/carrot.png",
                            Name = "Carrot",
                            Price = 50.00m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sweet golden corn on the cob, ready to boil or grill.",
                            Image = "image/product/corn.png",
                            Name = "Corn",
                            Price = 20.00m,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Fresh dill herb for seasoning and garnishing.",
                            Image = "image/product/dill.png",
                            Name = "Dill",
                            Price = 25.00m,
                            Unit = "bunch"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Fresh eggplant perfect for grilling or stir-frying.",
                            Image = "image/product/eggplant.png",
                            Name = "Eggplant",
                            Price = 40.00m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Aromatic garlic bulbs, essential for cooking.",
                            Image = "image/product/garlic.png",
                            Name = "Garlic",
                            Price = 80.00m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sweet seedless grapes, perfect for snacking.",
                            Image = "image/product/grapes.png",
                            Name = "Grapes",
                            Price = 20.50m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Fresh leeks with mild onion-like flavor.",
                            Image = "image/product/leek.png",
                            Name = "Leek",
                            Price = 70.00m,
                            Unit = "bunch"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Crisp green lettuce, ideal for salads and sandwiches.",
                            Image = "image/product/lettuce.png",
                            Name = "Lettuce",
                            Price = 10.20m,
                            Unit = "head"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Fresh, tangy lime perfect for drinks and cooking.",
                            Image = "image/product/lime.png",
                            Name = "Lime",
                            Price = 5.50m,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Sweet and juicy melon, perfect for desserts and snacks.",
                            Image = "image/product/melon.png",
                            Name = "Melon",
                            Price = 60.00m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Savory olives great for salads, pizzas, or snacking.",
                            Image = "image/product/olives.png",
                            Name = "Olives",
                            Price = 200.00m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Citrusy, juicy oranges full of vitamin C.",
                            Image = "image/product/orange.png",
                            Name = "Orange",
                            Price = 120.00m,
                            Unit = "dozen"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Sweet green peas, ideal for stir-fries and soups.",
                            Image = "image/product/peas.png",
                            Name = "Peas",
                            Price = 150.00m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Juicy ripe pears, naturally sweet and refreshing.",
                            Image = "image/product/pear.png",
                            Name = "Pear",
                            Price = 10.00m,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Tropical pineapple with sweet and tangy flavor.",
                            Image = "image/product/pineapple.png",
                            Name = "Pineapple",
                            Price = 80.00m,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Crisp radishes with a peppery flavor.",
                            Image = "image/product/radish.png",
                            Name = "Radish",
                            Price = 30.00m,
                            Unit = "bunch"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Exotic fruit with juicy, sweet-sour flesh.",
                            Image = "image/product/rambutan.png",
                            Name = "Rambutan",
                            Price = 120.00m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Fresh spinach leaves packed with nutrients.",
                            Image = "image/product/spinach.png",
                            Name = "Spinach",
                            Price = 10.80m,
                            Unit = "bunch"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Mild, slightly sweet turnip great for stews.",
                            Image = "image/product/turnip.png",
                            Name = "Turnip",
                            Price = 35.00m,
                            Unit = "kg"
                        });
                });

            modelBuilder.Entity("GreenGleam.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GreenGleam.Api.Data.Entities.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("GreenGleam.Api.Data.Entities.Order", b =>
                {
                    b.HasOne("GreenGleam.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenGleam.Api.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("GreenGleam.Api.Data.Entities.Order", "Order")
                        .WithMany("OderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GreenGleam.Api.Data.Entities.UserAddress", b =>
                {
                    b.HasOne("GreenGleam.Api.Data.Entities.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenGleam.Api.Data.Entities.Order", b =>
                {
                    b.Navigation("OderItems");
                });

            modelBuilder.Entity("GreenGleam.Api.Data.Entities.User", b =>
                {
                    b.Navigation("UserAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
